#
# SPDX-License-Identifier: MIT
# 
# Copyright (c) 2026 Manuel Hernández Méndez
# 
# Authors:
#   Manuel Hernández Méndez <maherme.dev@gmail.com>
# 
 
include ../../toolchain.mk
include ../common.mk

INCLUDES += -I../graphic/src \
			-I../graphicglut/src

LDFLAGS += -Wl,--wrap=graphRegisterPrint \
		   -Wl,--wrap=graphUnregisterPrint
