name: CICD

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install openGL and glut library
        run: |
          sudo apt-get update
          sudo apt-get install -y freeglut3-dev
      - name: Compile project
        run: make game QUIET=""

  unit_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install gcc 15
        run: |
          NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install gcc binutils
          BREW_GCC_BIN=$(brew --prefix)/bin/gcc-15
          BREW_GCOV_BIN=$(brew --prefix)/bin/gcov-15
          sudo ln -sf $BREW_GCC_BIN /usr/bin/gcc
          sudo ln -sf $(brew --prefix)/bin/g++-15 /usr/bin/g++
          sudo ln -sf $BREW_GCOV_BIN /usr/bin/gcov
          echo "CC=gcc" >> $GITHUB_ENV
          echo "GCOV=gcov" >> $GITHUB_ENV
          echo "/home/linuxbrew/.linuxbrew/opt/binutils/bin" >> $GITHUB_PATH
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH
          gcc --version
          g++ --version
          gcov --version
      - name: Install openGL and glut library
        run: |
          sudo apt-get update
          sudo apt-get install -y freeglut3-dev
      - name: Install cmocka
        run: |
          sudo apt-get install -y git cmake
          git clone https://gitlab.com/cmocka/cmocka.git
          cd cmocka
          git switch --detach cmocka-2.0.1
          cmake -S . -B build
          cmake --build build
          sudo cmake --install build
      - name: Install gcovr
        run: |
          make install_gcovr
      - name: Run unitary testing
        shell: bash
        run: |
          export C_INCLUDE_PATH=/usr/local/include:$C_INCLUDE_PATH
          export LIBRARY_PATH=/usr/local/lib:$LIBRARY_PATH
          export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
          make test QUIET=""
          make run-test QUIET=""
          make coverage QUIET=""
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: ./bin/cov

  publish_coverage:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: unit_test
    if: github.event_name != 'pull_request'
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
      - name: Create coverage badge
        uses: jaywcjlove/coverage-badges-cli@main
        with:
          style: flat
          source: ./coverage_report.json
          output: coverage/badges.svg
          jsonPath: line_percent
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
